# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from newPassword import Ui_Form1


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(641, 444)
        Form.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        Form.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        QtGui.QFontDatabase.addApplicationFont(
            ':/icons/resources/fonts/Lobster-Regular.ttf')
        QtGui.QFontDatabase.addApplicationFont(
            ':/icons/resources/fonts/BioRhyme-Regular.ttf')
        QtGui.QFontDatabase.addApplicationFont(
            ':/icons/resources/fonts/Roboto-Medium.ttf')
        QtGui.QFontDatabase.addApplicationFont(
            ':/icons/resources/fonts/Roboto-Regular.ttf')
        QtGui.QFontDatabase.addApplicationFont(
            ':/icons/resources/fonts/BerkshireSwash-Regular.ttf')
        QtGui.QFontDatabase.addApplicationFont(
            ':/icons/resources/fonts/Poppins-BoldItalic.ttf')
        QtGui.QFontDatabase.addApplicationFont(
            ':/icons/resources/fonts/Poppins-SemiBold.ttf.ttf')
        QtGui.QFontDatabase.addApplicationFont(
            ':/icons/resources/fonts/Poppins-Medium.ttf')
        QtGui.QFontDatabase.addApplicationFont(
            ':/icons/resources/fonts/Poppins-SemiBoldItalic.ttf')
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(30, 10, 590, 420))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(40, 25, 270, 360))
        self.label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(85, 98, 122, 255), stop:1 rgba(255, 107, 107, 255));\n"
                                 "border-radius: 10px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(290, 40, 260, 330))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                   "border-radius:15px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(330, 80, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setFamily("Poppins")
        font.setWeight(90)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgba(0, 0, 0, 200);")
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setGeometry(QtCore.QRect(330, 140, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
                                      "border:2px solid rgba(0, 0, 0, 0);\n"
                                      "border-bottom-color:rgba(46, 82, 101, 200);\n"
                                      "color:rgb(0, 0, 0);\n"
                                      "padding-bottom:7px;")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(330, 190, 191, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setFamily("Roboto Medium")
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton#pushButton{\n"
                                      "    background-color: rgba(85, 98, 112, 255);\n"
                                      "    color:rgba(255, 255, 255, 200);\n"
                                      "    border-radius:5px\n"
                                      "}\n"
                                      "QPushButton#pushButton:pressed{\n"
                                      "    padding-left:5px;\n"
                                      "    padding-top:5px;\n"
                                      "    background-color: rgba(255, 107, 107, 255);\n"
                                      "    background-position:calc(100% - 10px)center;\n"
                                      "}\n"
                                      "QPushButton#pushButton:hover{\n"
                                      "    background-color: rgba(255, 107, 107, 255);\n"
                                      "}\n"
                                      "")
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(330, 260, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(60, 50, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setFamily("Poppins")
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:rgba(255, 255, 255, 255)")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(136, 78, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setFamily("Poppins")
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:rgba(255, 255, 255, 255)")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(60, 120, 231, 141))
        self.label_7.setWordWrap(True)
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color:rgba(255, 255, 255, 220)")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setGeometry(QtCore.QRect(50, 250, 251, 121))
        font = QtGui.QFont()
        font.setFamily("Lobster")
        font.setPointSize(30)
        font.setLetterSpacing(1, 1)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color:rgba(77, 0, 51, 80);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(330, 290, 191, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setFamily("Roboto Medium")
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton#pushButton_2{\n"
                                        "    background-color: rgba(85, 98, 112, 255);\n"
                                        "    color:rgba(255, 255, 255, 200);\n"
                                        "    border-radius:5px\n"
                                        "}\n"
                                        "QPushButton#pushButton_2:pressed{\n"
                                        "    padding-left:5px;\n"
                                        "    padding-top:5px;\n"
                                        "    background-color: rgba(255, 107, 107, 255);\n"
                                        "    background-position:calc(100% - 10px)center;\n"
                                        "}\n"
                                        "QPushButton#pushButton_2:hover{\n"
                                        "    background-color: rgba(255, 107, 107, 255);\n"
                                        "}\n"
                                        "")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2.raise_()
        self.label.raise_()
        self.label_3.raise_()
        self.lineEdit_2.raise_()
        self.pushButton.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.closebutton = QtWidgets.QPushButton(self.widget)
        self.closebutton.setGeometry(QtCore.QRect(500, 50, 41, 31))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.closebutton.sizePolicy().hasHeightForWidth())
        self.closebutton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.closebutton.setFont(font)
        self.closebutton.setStyleSheet("QPushButton#closebutton{\n"
                                       "background-color: none;\n"
                                       "border: none;\n"
                                       "\n"
                                       "}\n"
                                       "\n"
                                       "\n"
                                       "QPushButton#closebutton:pressed{\n"
                                       "padding-left:5px;\n"
                                       "padding-top:5px;\n"
                                       "}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(
            ":/icons/resources/icons/close_button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closebutton.setIcon(icon)
        self.closebutton.setIconSize(QtCore.QSize(25, 25))
        self.closebutton.setText("")
        self.closebutton.setObjectName("closebutton")
        self.pushButton_2.raise_()
        self.closebutton.raise_()
        self.closebutton.clicked.connect(lambda: [Form.close()])

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.pushButton_2.clicked.connect(lambda: [self.newpass(Ui_Form1)])
        self.label.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(
            blurRadius=25, xOffset=0, yOffset=0))
        self.pushButton_2.setGraphicsEffect(
            QtWidgets.QGraphicsDropShadowEffect(blurRadius=25, xOffset=0, yOffset=0))
        self.pushButton.setGraphicsEffect(
            QtWidgets.QGraphicsDropShadowEffect(blurRadius=25, xOffset=0, yOffset=0))

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "Log In"))
        self.lineEdit_2.setToolTip(_translate(
            "Form", "<html><head/><body><p><span style=\" color:#7d9af7;\">Your master password. <br>Default password is \"123\".</span></p></body></html>"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "  Password"))
        self.pushButton.setText(_translate("Form", "Log In"))
        self.label_4.setText(_translate("Form", ""))
        self.label_4.setText(_translate("Form", "Want to set a new password?"))
        self.label_5.setText(_translate("Form", "Password"))
        self.label_6.setText(_translate("Form", "Manager"))
        self.label_7.setText(_translate("Form", "Best place to store your passwords, \n"
                                        "totally secure. \n"
                                        "\n"
                                        "Reliable fernet encryption,\n"
                                        "at your tips."))
        self.label_8.setText(_translate("Form", "Passwords.\n""Managed."))
        self.pushButton_2.setToolTip(_translate(
            "Form", "Forgot your Username/Password?"))
        self.pushButton_2.setText(_translate("Form", "New Password"))

    def newpass(self, Form):
        self.Form = QtWidgets.QWidget()
        self.ui = Ui_Form1()
        self.ui.setupUi(self.Form)
        self.Form.show()


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Form = QtWidgets.QWidget()
#     ui = Ui_Form()
#     ui.setupUi(Form)
#     Form.show()
#     sys.exit(app.exec_())
